### ISSUE TITLE
Quickjump: persistent file filter

### ISSUE THREAD

**Issue by vifon** [Klinkenstecker/ranger#1]
**Steps to reproduce**:
1. Call `scout -afQ`
2. Narrow down the search with a filter.
3. Select a directory (does not seem to work with the regular files) with Quickjump.

**What happens**:

The filter stays set (like when the `-p` option is set). If the directory gets selected without the use of Quickjump, the filter is being undone as usual.

**What was expected**:

The filter should be removed after performing chdir.

**Comment by Klinkenstecker** [comment]
I have fixed this issue now
